let car1 = "honda";
let car2 = "toyota";
let animal1 = "loin";
let animal2 = "fox";
let mountain1 = "everest";
let mountain2 = "k2";
let city1 = "mangla";
let city2 = "lahore";
let country1 = "pakistan";
let country2 = "india";

console.log("Is car1 == 'honda'?");
console.log("I predicted", car1 === "honda");
console.log("Is car2 == 'kia'?");
console.log("I predicted", car2 == "kia");
console.log("Is animal1 == 'loin'?");
console.log("I predicted", animal1 == "loin");
console.log("Is animal2 == 'tiger'?");
console.log("I predicted", animal2 == "tiger");
console.log("Is mountain1 == 'everest'?");
console.log("I predicted", mountain1 == "everest");
console.log("Is mountain2 == 'k2'?");
console.log("I predicted", mountain2 == "k2");
console.log("Is city1 == 'mangla'?");
console.log("I predicted", city1 == "mangla");
console.log("Is city2 == 'islamabad'?");
console.log("I predicted", city2 == "islamabad");
console.log("Is country1 == 'pakistan'?");
console.log("I predicted", country1 == "pakistan");
console.log("Is country2 == 'kashmir'?");
console.log("I predicted", country2 === "kashmir");
